services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AuHEExMqVHYUD0RTMqfs
      POSTGRES_DB: auth_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # persist postgres db data in the database folder

# Uncomment and add your changes to the following to add a pgadmin container
# pgadmin:
#   image: dpage/pgadmin4
#   container_name: pgadmin
#   depends_on:
#     - postgres
#   ports:
#     - "5050:80"
#   restart: always
#   environment:
#     PGADMIN_DEFAULT_EMAIL: your.email@nutrient.io
#     PGADMIN_DEFAULT_PASSWORD: your_password
#   volumes:
#     - ./pgadmin:/var/lib/pgadmin # persist pgadmin data in the database folder
